FROM maven:3.9.5-eclipse-temurin-21 AS build

WORKDIR /app

COPY votingApp/pom.xml .

RUN mvn dependency:go-offline

COPY votingApp/src ./src

RUN mvn clean package -DskipTests

FROM openjdk:21

WORKDIR /app

COPY --from=build /app/target/votingApp-0.0.1-SNAPSHOT.jar app.jar

COPY votingApp/.env .env

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]