version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: voting-app
      MYSQL_ROOT_PASSWORD: *****
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: voting-backend
    depends_on:
      - db
    environment:
      DATASOURCE_URL: jdbc:mysql://db:3306/voting-app
      DATASOURCE_USER: root
      DATASOURCE_PASSWORD: ******
      FRONTEND_URL: http://frontend
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: voting-frontend
    ports:
      - "80:80"

volumes:
  db_data:
